name: First Workflow

on : [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Hello
        run: echo "Hello from ${{github.orkflow}} by ${{github.actor}}"
